name: CI
on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
      - name: Run Python tests
        run: |
          poetry run pytest --cov=app --cov-fail-under=80

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install frontend deps
        run: |
          cd frontend
          pnpm install
      - name: Build frontend
        run: |
          cd frontend
          pnpm build
      - name: Run frontend tests
        run: |
          cd frontend
          pnpm test:e2e 