name: Dependabot Auto-merge

on:
  pull_request:
    # Only for Dependabot PRs
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run tests for non-patch updates
        if: steps.metadata.outputs.update-type != 'version-update:semver-patch'
        run: |
          echo "Running tests for ${{ steps.metadata.outputs.update-type }}"
          # Add your test commands here
          # This ensures major/minor updates are tested before auto-merge 